export default {
  translation: {
    messages: {
      key_zero: ' сообщений',
      key_one: ' сообщение',
      key_interval: '(2-4)[ сообщения];',
      key_many: ' сообщений',
      key_other: ' сообщений',
    },
    goTo: 'Но вы можете перейти ',
    pageNotFound: 'Страница не найдена',
    onMainPage: 'на главную страницу',
    channelControl: 'Управление каналом',
    addChanel: '+',
    nameChannel: 'Имя канала',
    haveAcount: 'Уже зарегистрированы? ',
    enter: 'Вход',
    entering: 'Войти',
    nameUser: 'Имя пользователя',
    youNick: 'Ваш ник',
    password: 'Пароль',
    confirmPassword: 'Подтвердите пароль',
    logo: 'Hexlet Chat',
    signUp: 'Регистрация',
    register: 'Зарегистрироваться',
    notAccount: 'Нет аккаунта? ',
    channels: 'Каналы',
    exit: 'Выйти',
    newMessage: 'Введите сообщение...',
    cancel: 'Отменить',
    send: 'Отправить',
    delet: 'Удалить',
    rename: 'Переименовать',
    deletLead: 'Уверены?',
    unknownError: 'Упс что-то пошло не так',
    titleModal: {
      add: 'Добавить канал',
      rename: 'Переименовать канал',
      remove: 'Удалить канал',
      none: 'Ошибка модального окна',
    },
    error: {
      duplicate: 'Имя канала должно быть уникальным',
      lengthError: 'Имя канала должно содержать не менее 3 и не более 20 символов',
      required: 'Поле должно быть заполнено',
      unknownError: 'Упс что-то пошло не так',
      badWord: 'Нецензурные слова запрещены',
    },
    errorlogin: {
      lengthError: 'От 3 до 20 символов',
      required: 'Поле должно быть заполнено',
      cloneLogin: 'Пользователь с таким именем уже существует',
      UnknownUser: 'Неверные имя пользователя или пароль',
    },
    errorPassword: {
      lengthError: 'Не менее 6 символов',
      required: 'Поле должно быть заполнено',
    },
    errorConfirmPassword: {
      mismatch: 'Пароли должны совпадать',
      required: 'Поле должно быть заполнено',
      lengthError: 'Не менее 6 символов',
    },
    toast: {
      NewChannel: 'Канал создан',
      RenameChannel: 'Канал переименован',
      RemoveChannel: 'Канал удалён',
    },
  },
};
